// This file is used to test the API using REST
GET http://localhost:3001/api/stats HTTP/1.1


###
GET http://localhost:3001/api/processes HTTP/1.1
###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}