name: release
on: 
  push:
    tags: 
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20.x'

      - name: Install dependencies client_interface
        working-directory: ./client_interface
        run: npm install

      - name: Build
        working-directory: ./client_interface
        run: npm run build

      - name: Install dependencies server
        working-directory: ./server
        run: npm install
      
      - name: Zip Server
        run: |
          rm -rf client_interface
          zip -r server.zip .

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: server.zip