name: release
on: 
  push:
    # tags: 
    #   - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            server/*
            constants.js
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false